name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build backend (skip tests to speed up packaging)
      - name: Build backend
        run: mvn -B clean package -DskipTests

      # Step 4: Run tests with H2 (or your test profile)
      - name: Run tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test
